apiVersion: v1
kind: Service
metadata:
  labels:
    service: ecars-client
  name: ecars-client
spec:
  ports:
  - name: "3003"
    port: 3003
    targetPort: 80
  selector:
    service: ecars-client
