version: "3.8"
services:
  reverseproxy:
      image: noiffion/ecars-revproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - ecars-cars
        - ecars-reviews
        - ecars-users
  ecars-cars:
    image: noiffion/ecars-cars
    tty: true
    env_file:
      - .env
  ecars-reviews:
    image: noiffion/ecars-reviews
    tty: true
    env_file:
      - .env
  ecars-users:
    image: noiffion/ecars-users
    tty: true
    env_file:
      - .env
  ecars-client:
    image: noiffion/ecars-client
    ports:
      - "3003:80"
