version: "3.8"
services:
  ecars-revproxy:
    build:
      context: .
    image: noiffion/ecars-revproxy
  ecars-cars:
    build:
      context: ../../cars
    image: noiffion/ecars-cars
  ecars-reviews:
    build:
      context: ../../reviews
    image: noiffion/ecars-reviews
  ecars-users:
    build:
      context: ../../users
    image: noiffion/ecars-users
  ecars-client:
    build:
      context: ../../client
    image: noiffion/ecars-client
