apiVersion: v1
kind: Service
metadata:
  labels:
    service: ecars-reviews
  name: ecars-reviews
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: ecars-reviews