apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ecars-revproxy
  name: ecars-revproxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: ecars-revproxy
  template:
    metadata:
      labels:
        service: ecars-revproxy
    spec:
      containers:
      - image: noiffion/ecars-revproxy
        name: ecars-revproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
